In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [3]:
lrModel = LogisticRegression(max_iter=10000)

In [4]:
lrModel.fit(x_train, y_train)

LogisticRegression(max_iter=10000)

In [5]:
lrModel.score(x_test, y_test)

0.9574074074074074

In [6]:
svm = SVC()

In [7]:
svm.fit(x_train, y_train)

SVC()

In [8]:
svm.score(x_test, y_test)

0.9814814814814815

In [9]:
rfmodel = RandomForestClassifier(n_estimators=40)
rfmodel.fit(x_train, y_train)

RandomForestClassifier(n_estimators=40)

In [10]:
rfmodel.score(x_test, y_test)

0.9537037037037037

In [11]:
from sklearn.model_selection import KFold

In [12]:
KFold(n_splits=10,random_state=None,shuffle=False)

KFold(n_splits=10, random_state=None, shuffle=False)

In [13]:
array = np.array([1,2,3,4,5,6,7,8,9])
for train_index, test_index in KFold(n_splits=3).split(array):
    print(array[train_index],array[test_index])

[4 5 6 7 8 9] [1 2 3]
[1 2 3 7 8 9] [4 5 6]
[1 2 3 4 5 6] [7 8 9]


In [14]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [23]:
scores_logistic = []
scores_svm = []
scores_rf = []
for train_index, test_index in KFold(n_splits=3,shuffle= False,random_state=None).split(digits.data,digits.target):
    X_train, X_test, Y_train, Y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(max_iter=10000),X_train,X_test,Y_train,Y_test))
    scores_svm.append(get_score(SVC(),X_train,X_test,Y_train,Y_test))
    scores_rf.append(get_score(RandomForestClassifier(),X_train,X_test,Y_train,Y_test))

In [16]:
scores_logistic

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [17]:
scores_rf

[0.9348914858096828, 0.9582637729549248, 0.9265442404006677]

In [18]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [19]:
from sklearn.model_selection import cross_val_score

In [20]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)


array([0.89482471, 0.95325543, 0.90984975])

In [21]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)


array([0.38063439, 0.41068447, 0.51252087])

In [22]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)


array([0.92487479, 0.96327212, 0.92487479])